### PR TITLE
Add missing Mystical Agriculture crops

### PR DESCRIPTION
**Pull request by thelightcosine**
This adds some mystical Agriculture crops that were missing from Botany Pots. It also adds the two Mystical Agraddtions crops

I've tested these additions in Global Data Pack, and they all seem to work. 
There are, no doubt, other MysticalAg seeds still missing, but these are the ones that 'crop up' in the Valhelsia 2 modpack.

### CODE REVIEW

**Comment by Darkhax** [comment]
Thanks for helping contribute to this mod. Do you know if these missing seeds are only made available when certain items are loaded into the game? It's important for the mod and the seed item defined to actually exist otherwise there will be a big error in the logs. The conditions I have now check if the base mod is loading but doesn't check for the items themselves. Also what were the two agradition seeds?

Edit: Mainly keeping this note here for myself. 
```json
{
    "condition": "forge:item_exists",
    "item": "modid:item"
}
```

**Comment by thelightcosine** [comment]
i'm a doofus and didn't commit the Mystical Agradditions crops in the first commit.

So I believe that the way MysticalAgriculture works for mod resource crops is that it actually checks for the resource in oredict. I don't know how to do that in this data format. Unfortunately Java is not a language I'm expert at, and I've never actually done any modding myself. If there's a syntax for an oredict lookup in the conditions I can try and get them added though.

**Comment by thelightcosine** [comment]
oh, I guess I could just check the `item_exists` on the seed itself though, duh.

**Comment by thelightcosine** [comment]
So switching from `forge:mod_loaded` to `forge:item_exists` causes the recipes to not work anymore...

**Comment by thelightcosine** [comment]
Arg, so the MysticalAgradditions crops also aren't working. I swear they were before, but I've screwed something up and now they don't take effect.

**Comment by thelightcosine** [comment]
So i think I've got all the other ones handled now. MysticalAgriculture adds a condition you can use like this:

```json
    {
      "type": "mysticalagriculture:crop_enabled",
      "crop": "mysticalagriculture:aluminum"
    }
```

The two MysticalAgradditions ones still aren't working for some reason, it's driving me crazy

**Comment by thelightcosine** [comment]
@Darkhax should all be working now, and should only load the recipe if the corresponding MysticalAgriculture crop is enabled.

**Comment by Darkhax** [comment]
Im not sure you can use conditions added by other mods here. If mystical agriculture is not installed the type will probably throw an error. Have you tested without mystical agriculture as well?

**Comment by thelightcosine** [comment]
@Darkhax tested against a copy of the modpack with MysticalAgriculture and MysticalAgradditions turned off and it worked fine. Nothing in the logs, everything loaded up just fine and botanypots still functions as expected.

**Comment by Darkhax** [comment]
Okay cool, thanks for testing this out.

**Comment by Darkhax** [comment]
👀 

```
[16:09:10] [Server thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe mysticalagriculture:crops/nether_star
com.google.gson.JsonSyntaxException: Unknown condition type: mysticalagriculture:crop_enabled
	at net.minecraftforge.common.crafting.CraftingHelper.getCondition(CraftingHelper.java:225) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:214) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:203) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:56) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:37) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.resources.ReloadListener.lambda$reload$1(ReloadListener.java:14) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_222] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_222] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_222] {}
	at net.minecraft.resources.AsyncReloader.lambda$null$3(AsyncReloader.java:66) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(TickDelayedTask.java:20) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:140) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:759) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:141) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:110) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.driveOneInternal(MinecraftServer.java:742) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.driveOne(MinecraftServer.java:736) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:123) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.loadDataPacks(MinecraftServer.java:1583) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.reload(MinecraftServer.java:1559) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.command.impl.ReloadCommand.lambda$register$1(ReloadCommand.java:14) ~[forge-1.15.2-31.1.44_mapped_snapshot_20200406-1.15.1-recomp.jar:?] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[brigadier-1.0.17.jar:?] {}
	at net.minecraft.command.Commands.handleCommand(Commands.java:210) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.handleSlashCommand(ServerPlayNetHandler.java:1033) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.processChatMessage(ServerPlayNetHandler.java:1013) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.processPacket(CChatMessagePacket.java:40) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.processPacket(CChatMessagePacket.java:8) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:19) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(TickDelayedTask.java:20) [?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:140) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) [?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:759) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:110) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.driveOneInternal(MinecraftServer.java:742) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.driveOne(MinecraftServer.java:736) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:123) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.runScheduledTasks(MinecraftServer.java:722) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:666) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
```

**Comment by thelightcosine** [comment]
erf. Why didn't I get those same errors? Sorry about that mate...You can revert, and I'll take another look at it

**Comment by Darkhax** [comment]
lol, don't worry. I added some additional conditions which fixed it. It seems Forge checks the first condition before attempting to read the second condition. So if the first condition fails no error message.

**Pull request merged**
