### PR TITLE
Regions Unexplored Compat (1.18.2)

### PR DESCRIPTION
**Pull request by ChiefArug**
The rest of https://github.com/Darkhax-Minecraft/BotanyTrees/pull/69. Fully solves https://github.com/Darkhax-Minecraft/BotanyPots/issues/339

Note that this likely cannot just be cherry picked to 1.20.1+ due to the mod having a big rewrite, and also likely will need changes for 1.19.2+

This PR also adds vanilla snow and powder snow as valid soils, due to Regions Unexplored having a grass that only grows on snow blocks. These use the soil category "snow", which seems to be free.

### CODE REVIEW

**Comment by ChiefArug** [comment]
This is ready for 1.18.2 now

**Comment by ChiefArug** [comment]
Scrap that, Intellij's git integration is being weird and didn't commit my saved changes, instead committing the originally copied file...
*there goes hours of work*

**Comment by ChiefArug** [comment]
*Now* its ready for 1.18.2

**Comment by Darkhax** [comment]
Thanks for the help!

**Pull request merged**
