### PR TITLE
Add Several Mod Crop Supports, Update Pam's HarvestCraft 2: Crops for 1.18.2+

### PR DESCRIPTION
**Pull request by PhweeDev**
This pull request consists of support to many mods which add a seed of some sort. They have all been tested and work properly, no crashes or anything of the sort. 

-Added complete Occultism support, adding the 1 crop.
-Added mostly-complete Thermal Cultivation support. 
-Added All You Can Eat support. adding the 5 crops.
-Added Simple Farming support. adding the 25+ crops.
-Added Mystical World support. adding the 1 crop.
-Added Supplementaries support. adding the 1 crop.
-Added missing Pam's HarvestCraft 2 Crops support. Adding 27 crops? I believe?
-Added Sprout support, adding 1 crop.
-Added Farmer's Delight support, adding 3 crops.
-Reimplemented Mystical Agriculture and Industrial Agriculture chances to get Fertilized Essence. Still at 0.01 chance. 
-Added Ravage and Cabbage support. adding 1 crop.
-Added Industrial Agriculture crops, adding 20+ crops. 

Support should be forward-portable. There were built on 1.18.2's support. Dunno if it's easy to forwardport.

### CODE REVIEW

**Comment by Darkhax** [comment]
Thanks for working on this, I appreciate all your help. I've gone through all the files and noticed a few issues.

Mod support files require a load condition to prevent loading errors if the player does not have that mod installed. [Some of your files have this](https://github.com/Darkhax-Minecraft/BotanyPots/blob/901618be360ce702b3bc8ccc751d579c880b6964/Common/src/main/resources/data/botanypots/recipes/industrialagriculture/crop/bat.json#L2-L10) but most do not. Best practice is to include the ID of the seed and all of the drops from that crop. The following crops are missing this.

- allyoucaneat
- mysticalworld
- occultism
- ravageandcabbage
- simplefarming
- sprout
- supplementaries
- thermal

The FarmersDelight mod is a complicated situation. They want to have the addon support files in their mod and [have merged a PR for these files](https://github.com/vectorwing/FarmersDelight/pull/552), but they have not released in on CurseForge. For now I want to avoid any farmers delight files in the base mod while we sort this out.

The simplefarming honeydew file is misnamed [honerdew](https://github.com/Darkhax-Minecraft/BotanyPots/blob/901618be360ce702b3bc8ccc751d579c880b6964/Common/src/main/resources/data/botanypots/recipes/simplefarming/crop/honerdew.json) and the marshmallow file is misnamed [marshmellow](https://github.com/Darkhax-Minecraft/BotanyPots/blob/901618be360ce702b3bc8ccc751d579c880b6964/Common/src/main/resources/data/botanypots/recipes/simplefarming/crop/marshmellow.json).

The mystical agriculture file for [Obsidian has a formatting error](https://github.com/Darkhax-Minecraft/BotanyPots/blob/901618be360ce702b3bc8ccc751d579c880b6964/Common/src/main/resources/data/botanypots/recipes/mysticalagriculture/crop/obsidian.json#L34).

**Comment by Phweeeee** [comment]
Hey Darkhax,

I've pushed out 2 commits that should fix all of the issues you described in my pull request. If I've broken something or a format error is still found. Let me know.

-Phwee

**Comment by PhweeDev** [comment]
Hey Darkhax,

I've pushed out 5 commits that should fix all of the issues you described in my pull request. If I've broken something or a format error is still found. Let me know.

-Phwee

P.S: I sent you a FR on Discord, and I have completed testing out the changes I made, they do in fact work.  If you have any other mods, either for Botany Trees or Botany Pots. that you want compat for. Let me know. and I'll get to work on them immediately.

**Comment by Darkhax** [comment]
Thanks for making the changes. I've been sick and preparing for a move so I haven't been around much. Everything looks good, I am going to merge this now and hopefully nothing will explode.

**Pull request merged**
